### ISSUE TITLE
Setting the ticking volume to Zero does not stop the ticking noise

### ISSUE THREAD

**Issue by claremacrae** [bitegw/obsidian-pomodoro-widget#1]
Congratulations on your plugin being added to the Community Plugins list!

I've tried it out, and I've dragged the `Ticking volume` to 0:

![image](https://github.com/bitegw/obsidian-pomodoro-widget/assets/4840096/ffb714f0-85e2-4567-80ec-833b043573f8)

This is what the settings file looks like:

```
{
  "defaultTimerDuration": 25,
  "tickingSpeed": 1,
  "tickingVolume": 0,
  "alarmVolume": 0.296,
  "timerToggleLocation": "Ribbon icon",
  "widgetVisible": true,
  "widgetAnchor": "Bottom right",
  "widgetXOffset": 20,
  "widgetYOffset": 33.20159912109375
}
```

And yet I am still hearing the ticking.

It may be because the timer was already running?

No, I stopped the timer and restarted it, and it's still ticking, just a bit more quietly.

### Versions

Pomodoro Widget: 1.0.0
Obsidian: 1.5.8
OS: macOS Sonoma 14.2.1.

**Comment by claremacrae** [comment]
As a workaround, I've made this edit to the source of the installed plugin:

```diff
===================================================================
diff --git a/Migration Test/.obsidian/plugins/pomodoro-widget/main.js b/Migration Test/.obsidian/plugins/pomodoro-widget/main.js
--- a/Migration Test/.obsidian/plugins/pomodoro-widget/main.js	(revision bbbcac485a7d6579b4dd0c8e4326efbc1f9a0c51)
+++ b/Migration Test/.obsidian/plugins/pomodoro-widget/main.js	(date 1709241867380)
@@ -339,13 +339,13 @@
   stopTimer() {
     clearInterval(this.timerProcess);
     this.isTicking = false;
-    this.tickingSound.pause();
+    // this.tickingSound.pause(); // Commented out - see issue #1
     this.tickingSound.currentTime = 0;
     (0, import_obsidian2.setIcon)(this.playBtn, "play");
   }
   startTimer() {
     this.timerTimestamp = new Date(new Date().getTime() + new Date(this.timerRemainingTime).getTime());
-    this.tickingSound.play();
+    // this.tickingSound.play(); // Commented out - see issue #1
     this.isTicking = true;
     (0, import_obsidian2.setIcon)(this.playBtn, "pause");
     this.timerProcess = setInterval((label = this.timerTime) => {
```

**Comment by gvvim** [comment]
Thanks, and thank you for the bug report.

Does the issue persist after restarting the plugin or obsidian?
I wasn't able to recreate it or find an issue with the code, but I've add a setting to toggle the ticking sound that is unaffected by the volume in version 1.0.1, so you should be able to update and disable it that way.

**Comment by claremacrae** [comment]
> Does the issue persist after restarting the plugin or obsidian?

Yes it does.

Thank you, I will try the update.

**Comment by claremacrae** [comment]
Confirmed that 1.0.1 fixes it by enabling ticking to be turned off.

Many thanks.
